/*! Video.js v4.0.3 Copyright 2013 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */
 (function() {var b=void 0,f=!0,h=null,j=!1;function m(){return function(){}}function n(a){return function(){return this[a]}}function p(a){return function(){return a}}var r;document.createElement("video");document.createElement("audio");function s(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(s.da[a])return s.da[a];a=s.r(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new s.L(a,c,d)}var u=s;window.lc=window.mc=s;s.Ma="4.0";
s.lb="https:"==document.location.protocol?"https://":"http://";s.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},controlBar:{}}};"GENERATED_CDN_VSN"!==s.Ma&&(u.options.flash.swf=s.lb+"vjs.zencdn.net/"+s.Ma+"/video-js.swf");s.da={};s.O=s.CoreObject=m();
s.O.extend=function(a){var c,d;a=a||{};c=a.init||a.p||this.prototype.init||this.prototype.p||m();d=function(){c.apply(this,arguments)};d.prototype=s.f.create(this.prototype);d.prototype.constructor=d;d.extend=s.O.extend;d.create=s.O.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};s.O.create=function(){var a=s.f.create(this.prototype);this.apply(a,arguments);return a};
s.c=function(a,c,d){var e=s.getData(a);e.o||(e.o={});e.o[c]||(e.o[c]=[]);d.n||(d.n=s.n++);e.o[c].push(d);e.H||(e.disabled=j,e.H=function(c){if(!e.disabled){c=s.Wa(c);var d=e.o[c.type];if(d)for(var d=d.slice(0),l=0,t=d.length;l<t&&!c.ab();l++)d[l].call(a,c)}});1==e.o[c].length&&(document.addEventListener?a.addEventListener(c,e.H,j):document.attachEvent&&a.attachEvent("on"+c,e.H))};
s.A=function(a,c,d){if(s.$a(a)){var e=s.getData(a);if(e.o)if(c){var g=e.o[c];if(g){if(d){if(d.n)for(e=0;e<g.length;e++)g[e].n===d.n&&g.splice(e--,1)}else e.o[c]=[];s.Ta(a,c)}}else for(g in e.o)c=g,e.o[c]=[],s.Ta(a,c)}};s.Ta=function(a,c){var d=s.getData(a);0===d.o[c].length&&(delete d.o[c],document.removeEventListener?a.removeEventListener(c,d.H,j):document.detachEvent&&a.detachEvent("on"+c,d.H));s.Da(d.o)&&(delete d.o,delete d.H,delete d.disabled);s.Da(d)&&s.hb(a)};
s.Wa=function(a){function c(){return f}function d(){return j}if(!a||!a.Ea){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&"layerY"!==g&&(a[g]=e[g]);a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=j;a.Ca=c};a.Ca=d;a.stopPropagation=function(){e.stopPropagation&&e.stopPropagation();a.cancelBubble=f;a.Ea=c};a.Ea=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&
e.stopImmediatePropagation();a.ab=c;a.stopPropagation()};a.ab=d;if(a.clientX!=h){g=document.documentElement;var k=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||k&&k.scrollLeft||0)-(g&&g.clientLeft||k&&k.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||k&&k.scrollTop||0)-(g&&g.clientTop||k&&k.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
s.k=function(a,c){var d=s.$a(a)?s.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=s.Wa(c);d.H&&d.H.call(a,c);if(e&&!c.Ea())s.k(e,c);else if(!e&&!c.Ca()&&(d=s.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=j}return!c.Ca()};s.G=function(a,c,d){s.c(a,c,function(){s.A(a,c,arguments.callee);d.apply(this,arguments)})};var v=Object.prototype.hasOwnProperty;
s.d=function(a,c){var d=document.createElement(a||"div"),e;for(e in c)v.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};s.S=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};s.f={};s.f.create=Object.create||function(a){function c(){}c.prototype=a;return new c};s.f.U=function(a,c,d){for(var e in a)v.call(a,e)&&c.call(d||this,e,a[e])};s.f.v=function(a,c){if(!c)return a;for(var d in c)v.call(c,d)&&(a[d]=c[d]);return a};
s.f.Va=function(a,c){var d,e,g;a=s.f.copy(a);for(d in c)v.call(c,d)&&(e=a[d],g=c[d],a[d]=s.f.bb(e)&&s.f.bb(g)?s.f.Va(e,g):c[d]);return a};s.f.copy=function(a){return s.f.v({},a)};s.f.bb=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};s.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.n||(c.n=s.n++);e.n=d?d+"_"+c.n:c.n;return e};s.R={};s.n=1;s.expando="vdata"+(new Date).getTime();
s.getData=function(a){var c=a[s.expando];c||(c=a[s.expando]=s.n++,s.R[c]={});return s.R[c]};s.$a=function(a){a=a[s.expando];return!(!a||s.Da(s.R[a]))};s.hb=function(a){var c=a[s.expando];if(c){delete s.R[c];try{delete a[s.expando]}catch(d){a.removeAttribute?a.removeAttribute(s.expando):a[s.expando]=h}}};s.Da=function(a){for(var c in a)if(a[c]!==h)return j;return f};s.s=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
s.w=function(a,c){if(-1!=a.className.indexOf(c)){for(var d=a.className.split(" "),e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};s.pa=s.d("video");s.D=navigator.userAgent;s.pb=!!s.D.match(/iPhone/i);s.ob=!!s.D.match(/iPad/i);s.qb=!!s.D.match(/iPod/i);s.Na=s.pb||s.ob||s.qb;var w=s,x;var z=s.D.match(/OS (\d+)_/i);x=z&&z[1]?z[1]:b;w.Yb=x;s.ma=!!s.D.match(/Android.*AppleWebKit/i);var A=s,B=s.D.match(/Android (\d+)\./i);A.mb=B&&B[1]?B[1]:h;s.nb=function(){return!!s.D.match("Firefox")};
s.za=function(a){var c={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,k=d.length-1;0<=k;k--){e=d[k].name;g=d[k].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;c[e]=g}return c};s.ec=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};
s.Ba=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};s.Ja={};s.r=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};s.dc=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),k=Math.floor(c/60%60),l=Math.floor(c/3600),g=0<g||0<l?g+":":"";return g+(((g||10<=k)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};s.Zb=function(){document.body.focus();document.onselectstart=p(j)};s.kc=function(){document.onselectstart=p(f)};
s.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};s.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};s.xa=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
s.get=function(a,c,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(k){d(k)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(l){d&&d(l)}};s.Rb=function(a){try{var c=window.localStorage||j;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?s.log("LocalStorage Full (VideoJS)",d):18==d.code?s.log("LocalStorage not allowed (VideoJS)",d):s.log("LocalStorage Error (VideoJS)",d)}};s.Ya=function(a){a.match(/^https?:\/\//)||(a=s.d("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
s.log=function(){s.log.history=s.log.history||[];s.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};s.cc=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0),top:c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0)}};
s.b=s.O.extend({p:function(a,c,d){this.e=a;this.g=s.f.copy(this.g);c=this.options(c);this.Aa=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+s.n++);this.Eb=c.name||h;this.a=c.el||this.d();this.u=[];this.wa={};this.Z={};if((a=this.g)&&a.children){var e=this;s.f.U(a.children,function(a,c){c!==j&&!c.loadEvent&&(e[a]=e.Y(a,c))})}this.J(d)}});r=s.b.prototype;
r.t=function(){if(this.u)for(var a=this.u.length-1;0<=a;a--)this.u[a].t&&this.u[a].t();this.Z=this.wa=this.u=h;this.A();this.a.parentNode&&this.a.parentNode.removeChild(this.a);s.hb(this.a);this.a=h};r.Nb=n("e");r.options=function(a){return a===b?this.g:this.g=s.f.Va(this.g,a)};r.d=function(a,c){return s.d(a,c)};r.r=n("a");r.id=n("Aa");r.name=n("Eb");r.children=n("u");
r.Y=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||s.S(e),c.name=e,d=new window.videojs[d](this.e||this,c)):d=a;this.u.push(d);"function"===typeof d.id&&(this.wa[d.id()]=d);(e=e||d.name&&d.name())&&(this.Z[e]=d);"function"===typeof d.el&&d.el()&&(this.T||this.a).appendChild(d.el());return d};
r.removeChild=function(a){"string"===typeof a&&(a=this.Z[a]);if(a&&this.u){for(var c=j,d=this.u.length-1;0<=d;d--)if(this.u[d]===a){c=f;this.u.splice(d,1);break}c&&(this.wa[a.id]=h,this.Z[a.name]=h,(c=a.r())&&c.parentNode===(this.T||this.a)&&(this.T||this.a).removeChild(a.r()))}};r.P=p("");r.c=function(a,c){s.c(this.a,a,s.bind(this,c));return this};r.A=function(a,c){s.A(this.a,a,c);return this};r.G=function(a,c){s.G(this.a,a,s.bind(this,c));return this};r.k=function(a,c){s.k(this.a,a,c);return this};
r.J=function(a){a&&(this.K?a.call(this):(this.ga===b&&(this.ga=[]),this.ga.push(a)));return this};r.ia=function(){this.K=f;var a=this.ga;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.ga=[];this.k("ready")}};r.s=function(a){s.s(this.a,a);return this};r.w=function(a){s.w(this.a,a);return this};r.show=function(){this.a.style.display="block";return this};r.V=function(){this.a.style.display="none";return this};r.M=function(){this.w("vjs-fade-out");this.s("vjs-fade-in");return this};
r.aa=function(){this.w("vjs-fade-in");this.s("vjs-fade-out");return this};r.cb=function(){this.s("vjs-lock-showing");return this};r.ja=function(){this.w("vjs-lock-showing");return this};r.disable=function(){this.V();this.show=m();this.M=m()};r.width=function(a,c){return C(this,"width",a,c)};r.height=function(a,c){return C(this,"height",a,c)};r.wb=function(a,c){return this.width(a,f).height(c)};
function C(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.k("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+s.S(c)],10)}
s.C=s.b.extend({p:function(a,c){s.b.call(this,a,c);var d=j;this.c("touchstart",function(){d=f});this.c("touchmove",function(){d=j});var e=this;this.c("touchend",function(a){d&&e.B(a);a.preventDefault();a.stopPropagation()});this.c("click",this.B);this.c("focus",this.fb);this.c("blur",this.eb)}});r=s.C.prototype;
r.d=function(a,c){c=s.f.v({className:this.P(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.$b||"Need Text")+"</span></div>",ic:"button","aria-live":"polite",tabIndex:0},c);return s.b.prototype.d.call(this,a,c)};r.P=function(){return"vjs-control "+s.b.prototype.P.call(this)};r.B=m();r.fb=function(){s.c(document,"keyup",s.bind(this,this.ca))};r.ca=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.B()};
r.eb=function(){s.A(document,"keyup",s.bind(this,this.ca))};s.Oa=s.b.extend();function D(a,c){a.Y(c);c.c("click",s.bind(a,function(){this.ja()}))}s.Oa.prototype.d=function(){var a=this.options().bc||"ul";this.T=s.d(a,{className:"vjs-menu-content"});a=s.b.prototype.d.call(this,"div",{append:this.T,className:"vjs-menu"});a.appendChild(this.T);s.c(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};s.na=s.C.extend({p:function(a,c){s.C.call(this,a,c);this.selected(c.selected)}});
s.na.prototype.d=function(a,c){return s.C.prototype.d.call(this,"li",s.f.v({className:"vjs-menu-item",innerHTML:this.g.label},c))};s.na.prototype.B=function(){this.selected(f)};s.na.prototype.selected=function(a){a?(this.s("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.w("vjs-selected"),this.a.setAttribute("aria-selected",j))};
s.sb=s.C.extend({p:function(a,c){s.C.call(this,a,c);var d=new s.Oa(this.e);this.options().title&&d.r().appendChild(s.d("li",{className:"vjs-menu-title",innerHTML:s.S(this.fc),jc:-1}));if(this.I=b)for(var e=0;e<this.I.length;e++)D(d,this.I[e]);this.ba=d;this.Y(this.ba);this.I&&0===this.I.length&&this.V();this.c("keyup",this.ca);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});r=s.sb.prototype;r.Q=j;r.P=function(){return this.className+" vjs-menu-button "+s.C.prototype.P.call(this)};
r.fb=m();r.eb=m();r.B=function(){this.G("mouseout",s.bind(this,function(){this.ba.ja();this.a.blur()}));this.Q?E(this):F(this)};r.ca=function(a){a.preventDefault();32==a.which||13==a.which?this.Q?E(this):F(this):27==a.which&&this.Q&&E(this)};function F(a){a.Q=f;a.ba.cb();a.a.setAttribute("aria-pressed",f);a.I&&0<a.I.length&&a.I[0].r().focus()}function E(a){a.Q=j;a.ba.ja();a.a.setAttribute("aria-pressed",j)}
s.L=s.b.extend({p:function(a,c,d){this.z=a;c=s.f.v(G(a),c);this.m={};this.gb=c.poster;this.$=c.controls;c.customControlsOnMobile!==f&&(s.Na||s.ma)?(a.controls=c.controls,this.$=j):a.controls=j;s.b.call(this,this,c,d);this.G("play",function(a){s.k(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.c("ended",this.Gb);this.c("play",this.Lb);this.c("firstplay",this.Ib);this.c("pause",this.Kb);this.c("progress",this.Mb);this.c("durationchange",
this.Fb);this.c("error",this.Hb);this.c("fullscreenchange",this.Jb);s.da[this.Aa]=this;c.plugins&&s.f.U(c.plugins,function(a,c){this[a](c)},this)}});r=s.L.prototype;r.g=s.options;r.t=function(){s.da[this.Aa]=h;this.z&&this.z.player&&(this.z.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.fa);this.W();this.j&&this.j.t();s.b.prototype.t.call(this)};
function G(a){var c={sources:[],tracks:[]};s.f.v(c,s.za(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,k=e.length;g<k;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?c.sources.push(s.za(a)):"track"===d&&c.tracks.push(s.za(a));return c}
r.d=function(){var a=this.a=s.b.prototype.d.call(this,"div"),c=this.z;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes())for(var d=c.childNodes.length,e=0,g=c.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&c.removeChild(g[0]);c.id=c.id||"vjs_video_"+s.n++;a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.s("vjs-paused");this.width(this.g.width,f);this.height(this.g.height,
f);c.parentNode&&c.parentNode.insertBefore(a,c);s.Ba(c,a);return a};
function H(a,c,d){a.j?(a.K=j,a.j.t(),a.Fa&&(a.Fa=j,clearInterval(a.fa)),a.Ga&&I(a),a.j=j):"Html5"!==c&&a.z&&(a.a.removeChild(a.z),a.z.Nb=h,a.z=h);a.X=c;a.K=j;var e=s.f.v({source:d,parentEl:a.a},a.g[c.toLowerCase()]);d&&(d.src==a.m.src&&0<a.m.currentTime&&(e.startTime=a.m.currentTime),a.m.src=d.src);a.j=new window.videojs[c](a,e);a.j.J(function(){this.e.ia();if(!this.l.Ha){var a=this.e;a.Fa=f;a.fa=setInterval(s.bind(a,function(){if(this.m.sa<this.buffered().end(0))this.k("progress");else if(1==(this.duration()?
this.buffered().end(0)/this.duration():0))clearInterval(this.fa),this.k("progress")}),500);a.j.G("progress",function(){this.l.Ha=f;var a=this.e;a.Fa=j;clearInterval(a.fa)})}this.l.Ka||(a=this.e,a.Ga=f,a.c("play",a.jb),a.c("pause",a.W),a.j.G("timeupdate",function(){this.l.Ka=f;I(this.e)}))})}function I(a){a.Ga=j;a.W();a.A("play",a.jb);a.A("pause",a.W)}r.jb=function(){this.Ua&&this.W();this.Ua=setInterval(s.bind(this,function(){this.k("timeupdate")}),250)};r.W=function(){clearInterval(this.Ua)};
r.Gb=function(){this.g.loop&&(this.currentTime(0),this.play())};r.Lb=function(){s.w(this.a,"vjs-paused");s.s(this.a,"vjs-playing")};r.Ib=function(){this.g.starttime&&this.currentTime(this.g.starttime)};r.Kb=function(){s.w(this.a,"vjs-playing");s.s(this.a,"vjs-paused")};r.Mb=function(){1==(this.duration()?this.buffered().end(0)/this.duration():0)&&this.k("loadedalldata")};r.Fb=function(){this.duration(J(this,"duration"))};r.Hb=function(a){s.log("Video Error",a)};
r.Jb=function(){this.F?this.s("vjs-fullscreen"):this.w("vjs-fullscreen")};function K(a,c,d){if(a.j&&a.j.K)a.j.J(function(){this[c](d)});else try{a.j[c](d)}catch(e){throw s.log(e),e;}}function J(a,c){if(a.j.K)try{return a.j[c]()}catch(d){throw a.j[c]===b?s.log("Video.js: "+c+" method not defined for "+a.X+" playback technology.",d):"TypeError"==d.name?(s.log("Video.js: "+c+" unavailable on "+a.X+" playback technology element.",d),a.j.K=j):s.log(d),d;}}r.play=function(){K(this,"play");return this};
r.pause=function(){K(this,"pause");return this};r.paused=function(){return J(this,"paused")===j?j:f};r.currentTime=function(a){return a!==b?(this.m.gc=a,K(this,"setCurrentTime",a),this.Ga&&this.k("timeupdate"),this):this.m.currentTime=J(this,"currentTime")||0};r.duration=function(a){return a!==b?(this.m.duration=parseFloat(a),this):this.m.duration};r.buffered=function(){var a=J(this,"buffered"),c=this.m.sa=this.m.sa||0;a&&(0<a.length&&a.end(0)!==c)&&(c=a.end(0),this.m.sa=c);return s.xa(0,c)};
r.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.m.volume=a,K(this,"setVolume",a),s.Rb(a),this;a=parseFloat(J(this,"volume"));return isNaN(a)?1:a};r.muted=function(a){return a!==b?(K(this,"setMuted",a),this):J(this,"muted")||j};r.ha=function(){return J(this,"supportsFullScreen")||j};
r.Ia=function(){var a=s.Ja.Ia;this.F=f;a?(s.c(document,a.ya,s.bind(this,function(c){this.F=document[a.F];this.F===j&&s.A(document,a.ya,arguments.callee);this.k("fullscreenchange")})),this.a[a.ib]()):this.j.ha()?K(this,"enterFullScreen"):(this.Cb=f,this.xb=document.documentElement.style.overflow,s.c(document,"keydown",s.bind(this,this.Xa)),document.documentElement.style.overflow="hidden",s.s(document.body,"vjs-full-window"),this.k("enterFullWindow"),this.k("fullscreenchange"));return this};
r.Xa=function(a){if(27===a.keyCode)if(this.F===f)if(a=s.Ja.Ia,this.F=j,a)document[a.ua]();else this.j.ha()?K(this,"exitFullScreen"):(L(this),this.k("fullscreenchange"));else L(this)};function L(a){a.Cb=j;s.A(document,"keydown",a.Xa);document.documentElement.style.overflow=a.xb;s.w(document.body,"vjs-full-window");a.k("exitFullWindow")}
r.src=function(a){if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.g.techOrder;d<e.length;d++){var g=s.S(e[d]),k=window.videojs[g];if(k.isSupported())for(var l=0,t=c;l<t.length;l++){var q=t[l];if(k.canPlaySource(q)){c={source:q,j:g};break a}}}c=j}c?(a=c.source,c=c.j,c==this.X?this.src(a):H(this,c,a)):this.a.appendChild(s.d("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.X].canPlaySource(a)?this.src(a.src):this.src([a]):(this.m.src=a,this.K?(K(this,"src",a),"auto"==this.g.preload&&this.load(),this.g.autoplay&&this.play()):this.J(function(){this.src(a)}));return this};r.load=function(){K(this,"load");return this};r.currentSrc=function(){return J(this,"currentSrc")||this.m.src||""};r.ea=function(a){return a!==b?(K(this,"setPreload",a),this.g.preload=a,this):J(this,"preload")};
r.autoplay=function(a){return a!==b?(K(this,"setAutoplay",a),this.g.autoplay=a,this):J(this,"autoplay")};r.loop=function(a){return a!==b?(K(this,"setLoop",a),this.g.loop=a,this):J(this,"loop")};r.poster=function(a){a!==b&&(this.gb=a);return this.gb};r.controls=function(a){a!==b&&this.$!==a&&(this.$=!!a,this.k("controlschange"));return this.$};var M,N,O;O=document.createElement("div");N={};
O.ac!==b?(N.ib="requestFullscreen",N.ua="exitFullscreen",N.ya="fullscreenchange",N.F="fullScreen"):(document.mozCancelFullScreen?(M="moz",N.F=M+"FullScreen"):(M="webkit",N.F=M+"IsFullScreen"),O[M+"RequestFullScreen"]&&(N.ib=M+"RequestFullScreen",N.ua=M+"CancelFullScreen"),N.ya=M+"fullscreenchange");document[N.ua]&&(s.Ja.Ia=N);
s.N=s.b.extend({p:function(a,c){s.b.call(this,a,c);a.controls()||this.disable();a.G("play",s.bind(this,function(){var a,c=s.bind(this,this.M),g=s.bind(this,this.aa);this.M();"ontouchstart"in window||(this.e.c("mouseover",c),this.e.c("mouseout",g),this.e.c("pause",s.bind(this,this.cb)),this.e.c("play",s.bind(this,this.ja)));a=j;this.e.c("touchstart",function(){a=f});this.e.c("touchmove",function(){a=j});this.e.c("touchend",s.bind(this,function(c){var e;a&&(e=this.r().className.search("fade-in"),-1!==
e?this.aa():this.M());a=j;this.e.paused()||c.preventDefault()}))}))}});s.N.prototype.g={hc:"play",children:{}};s.N.prototype.d=function(){return s.d("div",{className:"vjs-control-bar"})};s.N.prototype.M=function(){s.b.prototype.M.call(this);this.e.k("controlsvisible")};s.N.prototype.aa=function(){s.b.prototype.aa.call(this);this.e.k("controlshidden")};
s.Qa=s.b.extend({p:function(a,c){s.b.call(this,a,c);a.j&&(a.j.l&&a.j.l.La===j)&&this.s("vjs-hidden");a.c("loadstart",s.bind(this,function(){a.j.l&&a.j.l.La===j?this.s("vjs-hidden"):this.w("vjs-hidden")}))}});s.Qa.prototype.g={children:{volumeBar:{}}};s.Qa.prototype.d=function(){return s.b.prototype.d.call(this,"div",{className:"vjs-volume-control vjs-control"})};
s.qa=s.Pa.extend({p:function(a,c){s.Pa.call(this,a,c);a.c("volumechange",s.bind(this,this.kb));a.J(s.bind(this,this.kb));setTimeout(s.bind(this,this.update),0)}});s.qa.prototype.kb=function(){this.a.setAttribute("aria-valuenow",s.round(100*this.e.volume(),2));this.a.setAttribute("aria-valuetext",s.round(100*this.e.volume(),2)+"%")};s.qa.prototype.g={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};
s.qa.prototype.d=function(){return s.Pa.prototype.d.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};s.Ra=s.b.extend({p:function(a,c){s.b.call(this,a,c)}});s.Ra.prototype.d=function(){return s.b.prototype.d.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};s.ub=s.tb.extend();s.ub.prototype.d=function(){return s.tb.prototype.d.call(this,"div",{className:"vjs-volume-handle"})};
s.q=s.b.extend({p:function(a,c,d){s.b.call(this,a,c,d)}});s.q.prototype.B=s.ma?m():function(){this.e.controls()&&(this.e.paused()?this.e.play():this.e.pause())};s.q.prototype.l={La:f,Bb:j,Ha:j,Ka:j};s.media={};s.media.ka="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function P(){var a=s.media.ka[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=s.media.ka.length-1;0<=i;i--)s.q.prototype[s.media.ka[i]]=P();
s.i=s.q.extend({p:function(a,c,d){this.l.La=s.i.vb();this.l.Db=!s.Na;this.l.Bb=f;s.q.call(this,a,c,d);(c=c.source)&&this.a.currentSrc==c.src?a.k("loadstart"):c&&(this.a.src=c.src);a.J(function(){this.g.autoplay&&this.paused()&&(this.z.poster=h,this.play())});this.c("click",this.B);for(a=s.i.la.length-1;0<=a;a--)s.c(this.a,s.i.la[a],s.bind(this.e,this.zb));this.ia()}});r=s.i.prototype;r.t=function(){s.q.prototype.t.call(this)};
r.d=function(){var a=this.e,c=a.z;if(!c||this.l.Db===j)c?(c.player=h,a.z=h,a.r().removeChild(c),c=c.cloneNode(j)):c=s.d("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,s.Ba(c,a.r());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.g[g]!==h&&(c[g]=a.g[g])}return c};r.zb=function(a){this.k(a);a.stopPropagation()};r.play=function(){this.a.play()};r.pause=function(){this.a.pause()};r.paused=function(){return this.a.paused};r.currentTime=function(){return this.a.currentTime};
r.Qb=function(a){try{this.a.currentTime=a}catch(c){s.log(c,"Video is not ready. (Video.js)")}};r.duration=function(){return this.a.duration||0};r.buffered=function(){return this.a.buffered};r.volume=function(){return this.a.volume};r.Vb=function(a){this.a.volume=a};r.muted=function(){return this.a.muted};r.Tb=function(a){this.a.muted=a};r.width=function(){return this.a.offsetWidth};r.height=function(){return this.a.offsetHeight};
r.ha=function(){return"function"==typeof this.a.webkitEnterFullScreen&&(/Android/.test(s.D)||!/Chrome|Mac OS X 10.5/.test(s.D))?f:j};r.src=function(a){this.a.src=a};r.load=function(){this.a.load()};r.currentSrc=function(){return this.a.currentSrc};r.ea=function(){return this.a.ea};r.Ub=function(a){this.a.ea=a};r.autoplay=function(){return this.a.autoplay};r.Pb=function(a){this.a.autoplay=a};r.loop=function(){return this.a.loop};r.Sb=function(a){this.a.loop=a};s.i.isSupported=function(){return!!document.createElement("video").canPlayType};
s.i.ta=function(a){return!!document.createElement("video").canPlayType(a.type)};s.i.vb=function(){var a=s.pa.volume;s.pa.volume=a/2+0.1;return a!==s.pa.volume};s.i.la="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
s.ma&&3>s.mb&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
s.h=s.q.extend({p:function(a,c,d){s.q.call(this,a,c,d);d=c.source;var e=c.parentEl,g=this.a=s.d("div",{id:a.id()+"_temp_flash"}),k=a.id()+"_flash_api";a=a.g;var l=s.f.v({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.ea,loop:a.loop,muted:a.muted},c.flashVars),t=s.f.v({wmode:"opaque",bgcolor:"#000000"},c.params),q=s.f.v({id:k,name:k,"class":"vjs-tech"},c.attributes);d&&(l.src=encodeURIComponent(s.Ya(d.src)));
s.Ba(g,e);c.startTime&&this.J(function(){this.load();this.play();this.currentTime(c.startTime)});if(c.iFrameMode===f&&!s.nb){var y=s.d("iframe",{id:k+"_iframe",name:k+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});l.readyFunction="ready";l.eventProxyFunction="events";l.errorEventProxyFunction="errors";s.c(y,"load",s.bind(this,function(){var a,d=y.contentWindow;a=y.contentDocument?y.contentDocument:y.contentWindow.document;a.write(s.h.Za(c.swf,l,t,q));d.player=
this.e;d.ready=s.bind(this.e,function(c){c=a.getElementById(c);var d=this.j;d.a=c;s.c(c,"click",d.bind(d.B));s.h.va(d)});d.events=s.bind(this.e,function(a,c){this&&"flash"===this.X&&this.k(c)});d.errors=s.bind(this.e,function(a,c){s.log("Flash Error",c)})}));g.parentNode.replaceChild(y,g)}else s.h.yb(c.swf,g,l,t,q)}});r=s.h.prototype;r.t=function(){s.q.prototype.t.call(this)};r.play=function(){this.a.vjs_play()};r.pause=function(){this.a.vjs_pause()};
r.src=function(a){a=s.Ya(a);this.a.vjs_src(a);if(this.e.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};r.load=function(){this.a.vjs_load()};r.poster=function(){this.a.vjs_getProperty("poster")};r.buffered=function(){return s.xa(0,this.a.vjs_getProperty("buffered"))};r.ha=p(j);var Q=s.h.prototype,R="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),S="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");
function T(){var a=R[U],c=a.charAt(0).toUpperCase()+a.slice(1);Q["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}function V(a){Q[a]=function(){return this.a.vjs_getProperty(a)}}var U;for(U=0;U<R.length;U++)V(R[U]),T();for(U=0;U<S.length;U++)V(S[U]);s.h.isSupported=function(){return 10<=s.h.version()[0]};s.h.ta=function(a){if(a.type in s.h.Ab)return"maybe"};s.h.Ab={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};
s.h.onReady=function(a){a=s.r(a);var c=a.player||a.parentNode.player,d=c.j;a.player=c;d.a=a;d.c("click",d.B);s.h.va(d)};s.h.va=function(a){a.r().vjs_getProperty?a.ia():setTimeout(function(){s.h.va(a)},50)};s.h.onEvent=function(a,c){s.r(a).player.k(c)};s.h.onError=function(a,c){s.r(a).player.k("error");s.log("Flash Error",c,a)};
s.h.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
s.h.yb=function(a,c,d,e,g){a=s.h.Za(a,d,e,g);a=s.d("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var k=d.childNodes[0];setTimeout(function(){k.style.display="block"},1E3)};
s.h.Za=function(a,c,d,e){var g="",k="",l="";c&&s.f.U(c,function(a,c){g+=a+"="+c+"&amp;"});d=s.f.v({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);s.f.U(d,function(a,c){k+='<param name="'+a+'" value="'+c+'" />'});e=s.f.v({data:a,width:"100%",height:"100%"},e);s.f.U(e,function(a,c){l+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+l+">"+k+"</object>"};
s.rb=s.b.extend({p:function(a,c,d){s.b.call(this,a,c,d);if(!a.g.sources||0===a.g.sources.length){c=0;for(d=a.g.techOrder;c<d.length;c++){var e=s.S(d[c]),g=window.videojs[e];if(g&&g.isSupported()){H(a,e);break}}}else a.src(a.g.sources)}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)s.JSON=window.JSON;else{s.JSON={};var W=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;s.JSON.parse=function(a,c){function d(a,e){var l,t,q=a[e];if(q&&"object"===typeof q)for(l in q)Object.prototype.hasOwnProperty.call(q,l)&&(t=d(q,l),t!==b?q[l]=t:delete q[l]);return c.call(a,e,q)}var e;a=String(a);W.lastIndex=0;W.test(a)&&(a=a.replace(W,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
s.Sa=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==h&&(a=s.JSON.parse(a||"{}"),u(c,a)));else{s.ra();break}else s.Wb||s.ra()};s.ra=function(){setTimeout(s.Sa,1)};s.G(window,"load",function(){s.Wb=f});s.ra();s.oa=s.C.extend({p:function(a,c){s.C.call(this,a,c);(!a.poster()||!a.controls())&&this.V();a.c("play",s.bind(this,this.V))}});
s.oa.prototype.d=function(){var a=s.d("div",{className:"vjs-poster",tabIndex:-1}),c=this.e.poster();c&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+c+'")':a.appendChild(s.d("img",{src:c})));return a};s.oa.prototype.B=function(){this.e.play()};s.Ob=function(a,c){s.L.prototype[a]=c};var X=this;X.Xb=f;function Y(a,c){var d=a.split("."),e=X;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};Y("videojs",s);Y("_V_",s);Y("videojs.options",s.options);Y("videojs.cache",s.R);Y("videojs.Component",s.b);s.b.prototype.dispose=s.b.prototype.t;s.b.prototype.createEl=s.b.prototype.d;s.b.prototype.el=s.b.prototype.r;s.b.prototype.addChild=s.b.prototype.Y;s.b.prototype.children=s.b.prototype.children;s.b.prototype.on=s.b.prototype.c;s.b.prototype.off=s.b.prototype.A;s.b.prototype.one=s.b.prototype.G;s.b.prototype.trigger=s.b.prototype.k;s.b.prototype.triggerReady=s.b.prototype.ia;
s.b.prototype.show=s.b.prototype.show;s.b.prototype.hide=s.b.prototype.V;s.b.prototype.width=s.b.prototype.width;s.b.prototype.height=s.b.prototype.height;s.b.prototype.dimensions=s.b.prototype.wb;s.b.prototype.ready=s.b.prototype.J;Y("videojs.Player",s.L);s.L.prototype.dispose=s.L.prototype.t;Y("videojs.MediaLoader",s.rb);Y("videojs.ControlBar",s.N);Y("videojs.PosterImage",s.oa);Y("videojs.VolumeLevel",s.Ra);Y("videojs.MediaTechController",s.q);s.q.prototype.l.progressEvents=s.q.prototype.l.Ha;
s.q.prototype.l.timeupdateEvents=s.q.prototype.l.Ka;Y("videojs.Html5",s.i);s.i.Events=s.i.la;s.i.isSupported=s.i.isSupported;s.i.canPlaySource=s.i.ta;s.i.prototype.setCurrentTime=s.i.prototype.Qb;s.i.prototype.setVolume=s.i.prototype.Vb;s.i.prototype.setMuted=s.i.prototype.Tb;s.i.prototype.setPreload=s.i.prototype.Ub;s.i.prototype.setAutoplay=s.i.prototype.Pb;s.i.prototype.setLoop=s.i.prototype.Sb;Y("videojs.Flash",s.h);s.h.isSupported=s.h.isSupported;s.h.canPlaySource=s.h.ta;s.h.onReady=s.h.onReady;
Y("videojs.autoSetup",s.Sa);Y("videojs.plugin",s.Ob);Y("videojs.createTimeRange",s.xa);})();//@ sourceMappingURL=video.js.map
