/*! Video.js v4.0.3 Copyright 2013 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */
 (function() {var b=void 0,f=!0,h=null,j=!1;function m(){return function(){}}function n(a){return function(){return this[a]}}function q(a){return function(){return a}}var r;document.createElement("video");document.createElement("audio");function s(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(s.ca[a])return s.ca[a];a=s.p(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new s.L(a,c,d)}var u=s;window.dc=window.ec=s;s.Ja="4.0";
s.eb="https:"==document.location.protocol?"https://":"http://";s.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},controlBar:{}}};"GENERATED_CDN_VSN"!==s.Ja&&(u.options.flash.swf=s.eb+"vjs.zencdn.net/"+s.Ja+"/video-js.swf");s.ca={};s.O=s.CoreObject=m();
s.O.extend=function(a){var c,d;a=a||{};c=a.init||a.u||this.prototype.init||this.prototype.u||m();d=function(){c.apply(this,arguments)};d.prototype=s.d.create(this.prototype);d.prototype.constructor=d;d.extend=s.O.extend;d.create=s.O.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};s.O.create=function(){var a=s.d.create(this.prototype);this.apply(a,arguments);return a};
s.c=function(a,c,d){var e=s.getData(a);e.n||(e.n={});e.n[c]||(e.n[c]=[]);d.m||(d.m=s.m++);e.n[c].push(d);e.G||(e.disabled=j,e.G=function(c){if(!e.disabled){c=s.Qa(c);var d=e.n[c.type];if(d)for(var d=d.slice(0),l=0,t=d.length;l<t&&!c.Va();l++)d[l].call(a,c)}});1==e.n[c].length&&(document.addEventListener?a.addEventListener(c,e.G,j):document.attachEvent&&a.attachEvent("on"+c,e.G))};
s.z=function(a,c,d){if(s.Ua(a)){var e=s.getData(a);if(e.n)if(c){var g=e.n[c];if(g){if(d){if(d.m)for(e=0;e<g.length;e++)g[e].m===d.m&&g.splice(e--,1)}else e.n[c]=[];s.Na(a,c)}}else for(g in e.n)c=g,e.n[c]=[],s.Na(a,c)}};s.Na=function(a,c){var d=s.getData(a);0===d.n[c].length&&(delete d.n[c],document.removeEventListener?a.removeEventListener(c,d.G,j):document.detachEvent&&a.detachEvent("on"+c,d.G));s.Ba(d.n)&&(delete d.n,delete d.G,delete d.disabled);s.Ba(d)&&s.ab(a)};
s.Qa=function(a){function c(){return f}function d(){return j}if(!a||!a.Ca){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&"layerY"!==g&&(a[g]=e[g]);a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=j;a.Aa=c};a.Aa=d;a.stopPropagation=function(){e.stopPropagation&&e.stopPropagation();a.cancelBubble=f;a.Ca=c};a.Ca=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&
e.stopImmediatePropagation();a.Va=c;a.stopPropagation()};a.Va=d;if(a.clientX!=h){g=document.documentElement;var k=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||k&&k.scrollLeft||0)-(g&&g.clientLeft||k&&k.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||k&&k.scrollTop||0)-(g&&g.clientTop||k&&k.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
s.i=function(a,c){var d=s.Ua(a)?s.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=s.Qa(c);d.G&&d.G.call(a,c);if(e&&!c.Ca())s.i(e,c);else if(!e&&!c.Aa()&&(d=s.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=j}return!c.Aa()};s.F=function(a,c,d){s.c(a,c,function(){s.z(a,c,arguments.callee);d.apply(this,arguments)})};var v=Object.prototype.hasOwnProperty;
s.j=function(a,c){var d=document.createElement(a||"div"),e;for(e in c)v.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};s.S=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};s.d={};s.d.create=Object.create||function(a){function c(){}c.prototype=a;return new c};s.d.U=function(a,c,d){for(var e in a)v.call(a,e)&&c.call(d||this,e,a[e])};s.d.v=function(a,c){if(!c)return a;for(var d in c)v.call(c,d)&&(a[d]=c[d]);return a};
s.d.Pa=function(a,c){var d,e,g;a=s.d.copy(a);for(d in c)v.call(c,d)&&(e=a[d],g=c[d],a[d]=s.d.Wa(e)&&s.d.Wa(g)?s.d.Pa(e,g):c[d]);return a};s.d.copy=function(a){return s.d.v({},a)};s.d.Wa=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};s.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.m||(c.m=s.m++);e.m=d?d+"_"+c.m:c.m;return e};s.R={};s.m=1;s.expando="vdata"+(new Date).getTime();
s.getData=function(a){var c=a[s.expando];c||(c=a[s.expando]=s.m++,s.R[c]={});return s.R[c]};s.Ua=function(a){a=a[s.expando];return!(!a||s.Ba(s.R[a]))};s.ab=function(a){var c=a[s.expando];if(c){delete s.R[c];try{delete a[s.expando]}catch(d){a.removeAttribute?a.removeAttribute(s.expando):a[s.expando]=h}}};s.Ba=function(a){for(var c in a)if(a[c]!==h)return j;return f};s.s=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
s.A=function(a,c){if(-1!=a.className.indexOf(c)){for(var d=a.className.split(" "),e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};s.na=s.j("video");s.B=navigator.userAgent;s.ib=!!s.B.match(/iPhone/i);s.hb=!!s.B.match(/iPad/i);s.jb=!!s.B.match(/iPod/i);s.Ka=s.ib||s.hb||s.jb;var w=s,x;var z=s.B.match(/OS (\d+)_/i);x=z&&z[1]?z[1]:b;w.Qb=x;s.la=!!s.B.match(/Android.*AppleWebKit/i);var A=s,B=s.B.match(/Android (\d+)\./i);A.fb=B&&B[1]?B[1]:h;s.gb=function(){return!!s.B.match("Firefox")};
s.wa=function(a){var c={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,k=d.length-1;0<=k;k--){e=d[k].name;g=d[k].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;c[e]=g}return c};s.Xb=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};
s.za=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};s.Ha={};s.p=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};s.Wb=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),k=Math.floor(c/60%60),l=Math.floor(c/3600),g=0<g||0<l?g+":":"";return g+(((g||10<=k)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};s.Rb=function(){document.body.focus();document.onselectstart=q(j)};s.cc=function(){document.onselectstart=q(f)};
s.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};s.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};s.ua=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
s.get=function(a,c,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(k){d(k)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(l){d&&d(l)}};s.Ib=function(a){try{var c=window.localStorage||j;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?s.log("LocalStorage Full (VideoJS)",d):18==d.code?s.log("LocalStorage not allowed (VideoJS)",d):s.log("LocalStorage Error (VideoJS)",d)}};s.Sa=function(a){a.match(/^https?:\/\//)||(a=s.j("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
s.log=function(){s.log.history=s.log.history||[];s.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};s.Vb=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0),top:c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0)}};
s.b=s.O.extend({u:function(a,c,d){this.e=a;this.f=s.d.copy(this.f);c=this.options(c);this.ya=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+s.m++);this.vb=c.name||h;this.a=c.el||this.j();this.t=[];this.ta={};this.Y={};if((a=this.f)&&a.children){var e=this;s.d.U(a.children,function(a,c){c!==j&&!c.loadEvent&&(e[a]=e.X(a,c))})}this.K(d)}});r=s.b.prototype;
r.q=function(){if(this.t)for(var a=this.t.length-1;0<=a;a--)this.t[a].q&&this.t[a].q();this.Y=this.ta=this.t=h;this.z();this.a.parentNode&&this.a.parentNode.removeChild(this.a);s.ab(this.a);this.a=h};r.Eb=n("e");r.options=function(a){return a===b?this.f:this.f=s.d.Pa(this.f,a)};r.j=function(a,c){return s.j(a,c)};r.p=n("a");r.id=n("ya");r.name=n("vb");r.children=n("t");
r.X=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||s.S(e),c.name=e,d=new window.videojs[d](this.e||this,c)):d=a;this.t.push(d);"function"===typeof d.id&&(this.ta[d.id()]=d);(e=e||d.name&&d.name())&&(this.Y[e]=d);"function"===typeof d.el&&d.el()&&(this.T||this.a).appendChild(d.el());return d};
r.removeChild=function(a){"string"===typeof a&&(a=this.Y[a]);if(a&&this.t){for(var c=j,d=this.t.length-1;0<=d;d--)if(this.t[d]===a){c=f;this.t.splice(d,1);break}c&&(this.ta[a.id]=h,this.Y[a.name]=h,(c=a.p())&&c.parentNode===(this.T||this.a)&&(this.T||this.a).removeChild(a.p()))}};r.P=q("");r.c=function(a,c){s.c(this.a,a,s.bind(this,c));return this};r.z=function(a,c){s.z(this.a,a,c);return this};r.F=function(a,c){s.F(this.a,a,s.bind(this,c));return this};r.i=function(a,c){s.i(this.a,a,c);return this};
r.K=function(a){a&&(this.J?a.call(this):(this.fa===b&&(this.fa=[]),this.fa.push(a)));return this};r.ha=function(){this.J=f;var a=this.fa;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.fa=[];this.i("ready")}};r.s=function(a){s.s(this.a,a);return this};r.A=function(a){s.A(this.a,a);return this};r.show=function(){this.a.style.display="block";return this};r.xa=function(){this.a.style.display="none";return this};r.M=function(){this.A("vjs-fade-out");this.s("vjs-fade-in");return this};
r.$=function(){this.A("vjs-fade-in");this.s("vjs-fade-out");return this};r.Xa=function(){this.s("vjs-lock-showing");return this};r.ia=function(){this.A("vjs-lock-showing");return this};r.disable=function(){this.xa();this.show=m();this.M=m()};r.width=function(a,c){return C(this,"width",a,c)};r.height=function(a,c){return C(this,"height",a,c)};r.nb=function(a,c){return this.width(a,f).height(c)};
function C(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.i("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+s.S(c)],10)}
s.I=s.b.extend({u:function(a,c){s.b.call(this,a,c);var d=j;this.c("touchstart",function(){d=f});this.c("touchmove",function(){d=j});var e=this;this.c("touchend",function(a){d&&e.D(a);a.preventDefault();a.stopPropagation()});this.c("click",this.D);this.c("focus",this.Za);this.c("blur",this.Ya)}});r=s.I.prototype;
r.j=function(a,c){c=s.d.v({className:this.P(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.Sb||"Need Text")+"</span></div>",ac:"button","aria-live":"polite",tabIndex:0},c);return s.b.prototype.j.call(this,a,c)};r.P=function(){return"vjs-control "+s.b.prototype.P.call(this)};r.D=m();r.Za=function(){s.c(document,"keyup",s.bind(this,this.ba))};r.ba=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.D()};
r.Ya=function(){s.z(document,"keyup",s.bind(this,this.ba))};s.La=s.b.extend();function D(a,c){a.X(c);c.c("click",s.bind(a,function(){this.ia()}))}s.La.prototype.j=function(){var a=this.options().Ub||"ul";this.T=s.j(a,{className:"vjs-menu-content"});a=s.b.prototype.j.call(this,"div",{append:this.T,className:"vjs-menu"});a.appendChild(this.T);s.c(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};s.ma=s.I.extend({u:function(a,c){s.I.call(this,a,c);this.selected(c.selected)}});
s.ma.prototype.j=function(a,c){return s.I.prototype.j.call(this,"li",s.d.v({className:"vjs-menu-item",innerHTML:this.f.label},c))};s.ma.prototype.D=function(){this.selected(f)};s.ma.prototype.selected=function(a){a?(this.s("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.A("vjs-selected"),this.a.setAttribute("aria-selected",j))};
s.lb=s.I.extend({u:function(a,c){s.I.call(this,a,c);var d=new s.La(this.e);this.options().title&&d.p().appendChild(s.j("li",{className:"vjs-menu-title",innerHTML:s.S(this.Yb),bc:-1}));if(this.H=b)for(var e=0;e<this.H.length;e++)D(d,this.H[e]);this.aa=d;this.X(this.aa);this.H&&0===this.H.length&&this.xa();this.c("keyup",this.ba);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});r=s.lb.prototype;r.Q=j;r.P=function(){return this.className+" vjs-menu-button "+s.I.prototype.P.call(this)};
r.Za=m();r.Ya=m();r.D=function(){this.F("mouseout",s.bind(this,function(){this.aa.ia();this.a.blur()}));this.Q?E(this):F(this)};r.ba=function(a){a.preventDefault();32==a.which||13==a.which?this.Q?E(this):F(this):27==a.which&&this.Q&&E(this)};function F(a){a.Q=f;a.aa.Xa();a.a.setAttribute("aria-pressed",f);a.H&&0<a.H.length&&a.H[0].p().focus()}function E(a){a.Q=j;a.aa.ia();a.a.setAttribute("aria-pressed",j)}
s.L=s.b.extend({u:function(a,c,d){this.w=a;c=s.d.v(G(a),c);this.l={};this.$a=c.poster;this.Z=c.controls;c.customControlsOnMobile!==f&&(s.Ka||s.la)?(a.controls=c.controls,this.Z=j):a.controls=j;s.b.call(this,this,c,d);this.F("play",function(a){s.i(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.c("ended",this.xb);this.c("play",this.Cb);this.c("firstplay",this.zb);this.c("pause",this.Bb);this.c("progress",this.Db);this.c("durationchange",
this.wb);this.c("error",this.yb);this.c("fullscreenchange",this.Ab);s.ca[this.ya]=this;c.plugins&&s.d.U(c.plugins,function(a,c){this[a](c)},this)}});r=s.L.prototype;r.f=s.options;r.q=function(){s.ca[this.ya]=h;this.w&&this.w.player&&(this.w.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.ea);this.V();this.k&&this.k.q();s.b.prototype.q.call(this)};
function G(a){var c={sources:[],tracks:[]};s.d.v(c,s.wa(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,k=e.length;g<k;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?c.sources.push(s.wa(a)):"track"===d&&c.tracks.push(s.wa(a));return c}
r.j=function(){var a=this.a=s.b.prototype.j.call(this,"div"),c=this.w;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes())for(var d=c.childNodes.length,e=0,g=c.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&c.removeChild(g[0]);c.id=c.id||"vjs_video_"+s.m++;a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.s("vjs-paused");this.width(this.f.width,f);this.height(this.f.height,
f);c.parentNode&&c.parentNode.insertBefore(a,c);s.za(c,a);return a};
function H(a,c,d){a.k?(a.J=j,a.k.q(),a.Da&&(a.Da=j,clearInterval(a.ea)),a.Ea&&I(a),a.k=j):"Html5"!==c&&a.w&&(a.a.removeChild(a.w),a.w.Eb=h,a.w=h);a.W=c;a.J=j;var e=s.d.v({source:d,parentEl:a.a},a.f[c.toLowerCase()]);d&&(d.src==a.l.src&&0<a.l.currentTime&&(e.startTime=a.l.currentTime),a.l.src=d.src);a.k=new window.videojs[c](a,e);a.k.K(function(){this.e.ha();if(!this.r.Fa){var a=this.e;a.Da=f;a.ea=setInterval(s.bind(a,function(){if(this.l.pa<this.buffered().end(0))this.i("progress");else if(1==(this.duration()?
this.buffered().end(0)/this.duration():0))clearInterval(this.ea),this.i("progress")}),500);a.k.F("progress",function(){this.r.Fa=f;var a=this.e;a.Da=j;clearInterval(a.ea)})}this.r.Ia||(a=this.e,a.Ea=f,a.c("play",a.cb),a.c("pause",a.V),a.k.F("timeupdate",function(){this.r.Ia=f;I(this.e)}))})}function I(a){a.Ea=j;a.V();a.z("play",a.cb);a.z("pause",a.V)}r.cb=function(){this.Oa&&this.V();this.Oa=setInterval(s.bind(this,function(){this.i("timeupdate")}),250)};r.V=function(){clearInterval(this.Oa)};
r.xb=function(){this.f.loop&&(this.currentTime(0),this.play())};r.Cb=function(){s.A(this.a,"vjs-paused");s.s(this.a,"vjs-playing")};r.zb=function(){this.f.starttime&&this.currentTime(this.f.starttime)};r.Bb=function(){s.A(this.a,"vjs-playing");s.s(this.a,"vjs-paused")};r.Db=function(){1==(this.duration()?this.buffered().end(0)/this.duration():0)&&this.i("loadedalldata")};r.wb=function(){this.duration(J(this,"duration"))};r.yb=function(a){s.log("Video Error",a)};
r.Ab=function(){this.C?this.s("vjs-fullscreen"):this.A("vjs-fullscreen")};function K(a,c,d){if(a.k&&a.k.J)a.k.K(function(){this[c](d)});else try{a.k[c](d)}catch(e){throw s.log(e),e;}}function J(a,c){if(a.k.J)try{return a.k[c]()}catch(d){throw a.k[c]===b?s.log("Video.js: "+c+" method not defined for "+a.W+" playback technology.",d):"TypeError"==d.name?(s.log("Video.js: "+c+" unavailable on "+a.W+" playback technology element.",d),a.k.J=j):s.log(d),d;}}r.play=function(){K(this,"play");return this};
r.pause=function(){K(this,"pause");return this};r.paused=function(){return J(this,"paused")===j?j:f};r.currentTime=function(a){return a!==b?(this.l.Zb=a,K(this,"setCurrentTime",a),this.Ea&&this.i("timeupdate"),this):this.l.currentTime=J(this,"currentTime")||0};r.duration=function(a){return a!==b?(this.l.duration=parseFloat(a),this):this.l.duration};r.buffered=function(){var a=J(this,"buffered"),c=this.l.pa=this.l.pa||0;a&&(0<a.length&&a.end(0)!==c)&&(c=a.end(0),this.l.pa=c);return s.ua(0,c)};
r.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.l.volume=a,K(this,"setVolume",a),s.Ib(a),this;a=parseFloat(J(this,"volume"));return isNaN(a)?1:a};r.muted=function(a){return a!==b?(K(this,"setMuted",a),this):J(this,"muted")||j};r.ga=function(){return J(this,"supportsFullScreen")||j};
r.Ga=function(){var a=s.Ha.Ga;this.C=f;a?(s.c(document,a.va,s.bind(this,function(c){this.C=document[a.C];this.C===j&&s.z(document,a.va,arguments.callee);this.i("fullscreenchange")})),this.a[a.bb]()):this.k.ga()?K(this,"enterFullScreen"):(this.tb=f,this.ob=document.documentElement.style.overflow,s.c(document,"keydown",s.bind(this,this.Ra)),document.documentElement.style.overflow="hidden",s.s(document.body,"vjs-full-window"),this.i("enterFullWindow"),this.i("fullscreenchange"));return this};
r.Ra=function(a){if(27===a.keyCode)if(this.C===f)if(a=s.Ha.Ga,this.C=j,a)document[a.ra]();else this.k.ga()?K(this,"exitFullScreen"):(L(this),this.i("fullscreenchange"));else L(this)};function L(a){a.tb=j;s.z(document,"keydown",a.Ra);document.documentElement.style.overflow=a.ob;s.A(document.body,"vjs-full-window");a.i("exitFullWindow")}
r.src=function(a){if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=s.S(e[d]),k=window.videojs[g];if(k.isSupported())for(var l=0,t=c;l<t.length;l++){var p=t[l];if(k.canPlaySource(p)){c={source:p,k:g};break a}}}c=j}c?(a=c.source,c=c.k,c==this.W?this.src(a):H(this,c,a)):this.a.appendChild(s.j("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.W].canPlaySource(a)?this.src(a.src):this.src([a]):(this.l.src=a,this.J?(K(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):this.K(function(){this.src(a)}));return this};r.load=function(){K(this,"load");return this};r.currentSrc=function(){return J(this,"currentSrc")||this.l.src||""};r.da=function(a){return a!==b?(K(this,"setPreload",a),this.f.preload=a,this):J(this,"preload")};
r.autoplay=function(a){return a!==b?(K(this,"setAutoplay",a),this.f.autoplay=a,this):J(this,"autoplay")};r.loop=function(a){return a!==b?(K(this,"setLoop",a),this.f.loop=a,this):J(this,"loop")};r.poster=function(a){a!==b&&(this.$a=a);return this.$a};r.controls=function(a){a!==b&&this.Z!==a&&(this.Z=!!a,this.i("controlschange"));return this.Z};var M,N,O;O=document.createElement("div");N={};
O.Tb!==b?(N.bb="requestFullscreen",N.ra="exitFullscreen",N.va="fullscreenchange",N.C="fullScreen"):(document.mozCancelFullScreen?(M="moz",N.C=M+"FullScreen"):(M="webkit",N.C=M+"IsFullScreen"),O[M+"RequestFullScreen"]&&(N.bb=M+"RequestFullScreen",N.ra=M+"CancelFullScreen"),N.va=M+"fullscreenchange");document[N.ra]&&(s.Ha.Ga=N);
s.N=s.b.extend({u:function(a,c){s.b.call(this,a,c);a.controls()||this.disable();a.F("play",s.bind(this,function(){var a,c=s.bind(this,this.M),g=s.bind(this,this.$);this.M();"ontouchstart"in window||(this.e.c("mouseover",c),this.e.c("mouseout",g),this.e.c("pause",s.bind(this,this.Xa)),this.e.c("play",s.bind(this,this.ia)));a=j;this.e.c("touchstart",function(){a=f});this.e.c("touchmove",function(){a=j});this.e.c("touchend",s.bind(this,function(c){var e;a&&(e=this.p().className.search("fade-in"),-1!==
e?this.$():this.M());a=j;this.e.paused()||c.preventDefault()}))}))}});s.N.prototype.f={$b:"play",children:{}};s.N.prototype.j=function(){return s.j("div",{className:"vjs-control-bar"})};s.N.prototype.M=function(){s.b.prototype.M.call(this);this.e.i("controlsvisible")};s.N.prototype.$=function(){s.b.prototype.$.call(this);this.e.i("controlshidden")};s.o=s.b.extend({u:function(a,c,d){s.b.call(this,a,c,d)}});s.o.prototype.D=s.la?m():function(){this.e.controls()&&(this.e.paused()?this.e.play():this.e.pause())};
s.o.prototype.r={Nb:f,sb:j,Fa:j,Ia:j};s.media={};s.media.ja="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function P(){var a=s.media.ja[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=s.media.ja.length-1;0<=i;i--)s.o.prototype[s.media.ja[i]]=P();
s.h=s.o.extend({u:function(a,c,d){this.r.Nb=s.h.mb();this.r.ub=!s.Ka;this.r.sb=f;s.o.call(this,a,c,d);(c=c.source)&&this.a.currentSrc==c.src?a.i("loadstart"):c&&(this.a.src=c.src);a.K(function(){this.f.autoplay&&this.paused()&&(this.w.poster=h,this.play())});this.c("click",this.D);for(a=s.h.ka.length-1;0<=a;a--)s.c(this.a,s.h.ka[a],s.bind(this.e,this.qb));this.ha()}});r=s.h.prototype;r.q=function(){s.o.prototype.q.call(this)};
r.j=function(){var a=this.e,c=a.w;if(!c||this.r.ub===j)c?(c.player=h,a.w=h,a.p().removeChild(c),c=c.cloneNode(j)):c=s.j("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,s.za(c,a.p());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==h&&(c[g]=a.f[g])}return c};r.qb=function(a){this.i(a);a.stopPropagation()};r.play=function(){this.a.play()};r.pause=function(){this.a.pause()};r.paused=function(){return this.a.paused};r.currentTime=function(){return this.a.currentTime};
r.Hb=function(a){try{this.a.currentTime=a}catch(c){s.log(c,"Video is not ready. (Video.js)")}};r.duration=function(){return this.a.duration||0};r.buffered=function(){return this.a.buffered};r.volume=function(){return this.a.volume};r.Mb=function(a){this.a.volume=a};r.muted=function(){return this.a.muted};r.Kb=function(a){this.a.muted=a};r.width=function(){return this.a.offsetWidth};r.height=function(){return this.a.offsetHeight};
r.ga=function(){return"function"==typeof this.a.webkitEnterFullScreen&&(/Android/.test(s.B)||!/Chrome|Mac OS X 10.5/.test(s.B))?f:j};r.src=function(a){this.a.src=a};r.load=function(){this.a.load()};r.currentSrc=function(){return this.a.currentSrc};r.da=function(){return this.a.da};r.Lb=function(a){this.a.da=a};r.autoplay=function(){return this.a.autoplay};r.Gb=function(a){this.a.autoplay=a};r.loop=function(){return this.a.loop};r.Jb=function(a){this.a.loop=a};s.h.isSupported=function(){return!!document.createElement("video").canPlayType};
s.h.qa=function(a){return!!document.createElement("video").canPlayType(a.type)};s.h.mb=function(){var a=s.na.volume;s.na.volume=a/2+0.1;return a!==s.na.volume};s.h.ka="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
s.la&&3>s.fb&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
s.g=s.o.extend({u:function(a,c,d){s.o.call(this,a,c,d);d=c.source;var e=c.parentEl,g=this.a=s.j("div",{id:a.id()+"_temp_flash"}),k=a.id()+"_flash_api";a=a.f;var l=s.d.v({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.da,loop:a.loop,muted:a.muted},c.flashVars),t=s.d.v({wmode:"opaque",bgcolor:"#000000"},c.params),p=s.d.v({id:k,name:k,"class":"vjs-tech"},c.attributes);d&&(l.src=encodeURIComponent(s.Sa(d.src)));
s.za(g,e);c.startTime&&this.K(function(){this.load();this.play();this.currentTime(c.startTime)});if(c.iFrameMode===f&&!s.gb){var y=s.j("iframe",{id:k+"_iframe",name:k+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});l.readyFunction="ready";l.eventProxyFunction="events";l.errorEventProxyFunction="errors";s.c(y,"load",s.bind(this,function(){var a,d=y.contentWindow;a=y.contentDocument?y.contentDocument:y.contentWindow.document;a.write(s.g.Ta(c.swf,l,t,p));d.player=
this.e;d.ready=s.bind(this.e,function(c){c=a.getElementById(c);var d=this.k;d.a=c;s.c(c,"click",d.bind(d.D));s.g.sa(d)});d.events=s.bind(this.e,function(a,c){this&&"flash"===this.W&&this.i(c)});d.errors=s.bind(this.e,function(a,c){s.log("Flash Error",c)})}));g.parentNode.replaceChild(y,g)}else s.g.pb(c.swf,g,l,t,p)}});r=s.g.prototype;r.q=function(){s.o.prototype.q.call(this)};r.play=function(){this.a.vjs_play()};r.pause=function(){this.a.vjs_pause()};
r.src=function(a){a=s.Sa(a);this.a.vjs_src(a);if(this.e.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};r.load=function(){this.a.vjs_load()};r.poster=function(){this.a.vjs_getProperty("poster")};r.buffered=function(){return s.ua(0,this.a.vjs_getProperty("buffered"))};r.ga=q(j);var Q=s.g.prototype,R="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),S="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");
function T(){var a=R[U],c=a.charAt(0).toUpperCase()+a.slice(1);Q["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}function V(a){Q[a]=function(){return this.a.vjs_getProperty(a)}}var U;for(U=0;U<R.length;U++)V(R[U]),T();for(U=0;U<S.length;U++)V(S[U]);s.g.isSupported=function(){return 10<=s.g.version()[0]};s.g.qa=function(a){if(a.type in s.g.rb)return"maybe"};s.g.rb={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};
s.g.onReady=function(a){a=s.p(a);var c=a.player||a.parentNode.player,d=c.k;a.player=c;d.a=a;d.c("click",d.D);s.g.sa(d)};s.g.sa=function(a){a.p().vjs_getProperty?a.ha():setTimeout(function(){s.g.sa(a)},50)};s.g.onEvent=function(a,c){s.p(a).player.i(c)};s.g.onError=function(a,c){s.p(a).player.i("error");s.log("Flash Error",c,a)};
s.g.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
s.g.pb=function(a,c,d,e,g){a=s.g.Ta(a,d,e,g);a=s.j("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var k=d.childNodes[0];setTimeout(function(){k.style.display="block"},1E3)};
s.g.Ta=function(a,c,d,e){var g="",k="",l="";c&&s.d.U(c,function(a,c){g+=a+"="+c+"&amp;"});d=s.d.v({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);s.d.U(d,function(a,c){k+='<param name="'+a+'" value="'+c+'" />'});e=s.d.v({data:a,width:"100%",height:"100%"},e);s.d.U(e,function(a,c){l+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+l+">"+k+"</object>"};
s.kb=s.b.extend({u:function(a,c,d){s.b.call(this,a,c,d);if(!a.f.sources||0===a.f.sources.length){c=0;for(d=a.f.techOrder;c<d.length;c++){var e=s.S(d[c]),g=window.videojs[e];if(g&&g.isSupported()){H(a,e);break}}}else a.src(a.f.sources)}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)s.JSON=window.JSON;else{s.JSON={};var W=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;s.JSON.parse=function(a,c){function d(a,e){var l,t,p=a[e];if(p&&"object"===typeof p)for(l in p)Object.prototype.hasOwnProperty.call(p,l)&&(t=d(p,l),t!==b?p[l]=t:delete p[l]);return c.call(a,e,p)}var e;a=String(a);W.lastIndex=0;W.test(a)&&(a=a.replace(W,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
s.Ma=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==h&&(a=s.JSON.parse(a||"{}"),u(c,a)));else{s.oa();break}else s.Ob||s.oa()};s.oa=function(){setTimeout(s.Ma,1)};s.F(window,"load",function(){s.Ob=f});s.oa();s.Fb=function(a,c){s.L.prototype[a]=c};var X=this;X.Pb=f;function Y(a,c){var d=a.split("."),e=X;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};Y("videojs",s);Y("_V_",s);Y("videojs.options",s.options);Y("videojs.cache",s.R);Y("videojs.Component",s.b);s.b.prototype.dispose=s.b.prototype.q;s.b.prototype.createEl=s.b.prototype.j;s.b.prototype.el=s.b.prototype.p;s.b.prototype.addChild=s.b.prototype.X;s.b.prototype.children=s.b.prototype.children;s.b.prototype.on=s.b.prototype.c;s.b.prototype.off=s.b.prototype.z;s.b.prototype.one=s.b.prototype.F;s.b.prototype.trigger=s.b.prototype.i;s.b.prototype.triggerReady=s.b.prototype.ha;
s.b.prototype.show=s.b.prototype.show;s.b.prototype.hide=s.b.prototype.xa;s.b.prototype.width=s.b.prototype.width;s.b.prototype.height=s.b.prototype.height;s.b.prototype.dimensions=s.b.prototype.nb;s.b.prototype.ready=s.b.prototype.K;Y("videojs.Player",s.L);s.L.prototype.dispose=s.L.prototype.q;Y("videojs.MediaLoader",s.kb);Y("videojs.ControlBar",s.N);Y("videojs.MediaTechController",s.o);s.o.prototype.r.progressEvents=s.o.prototype.r.Fa;s.o.prototype.r.timeupdateEvents=s.o.prototype.r.Ia;
Y("videojs.Html5",s.h);s.h.Events=s.h.ka;s.h.isSupported=s.h.isSupported;s.h.canPlaySource=s.h.qa;s.h.prototype.setCurrentTime=s.h.prototype.Hb;s.h.prototype.setVolume=s.h.prototype.Mb;s.h.prototype.setMuted=s.h.prototype.Kb;s.h.prototype.setPreload=s.h.prototype.Lb;s.h.prototype.setAutoplay=s.h.prototype.Gb;s.h.prototype.setLoop=s.h.prototype.Jb;Y("videojs.Flash",s.g);s.g.isSupported=s.g.isSupported;s.g.canPlaySource=s.g.qa;s.g.onReady=s.g.onReady;Y("videojs.autoSetup",s.Ma);Y("videojs.plugin",s.Fb);
Y("videojs.createTimeRange",s.ua);})();//@ sourceMappingURL=video.js.map
